### PR TITLE
Add field support

### PR DESCRIPTION
**Pull request by jmbockhorst**
Adds field support and generate typings based on it. This makes it really nice to work with in the language server and simplifies so many things. I just used the fields I had/needed for type inference, but we can add more in the future. Feel free to adjust names as you see fit. 

The only breaking changes that I introduced was to removed `let`, `of`, `if`, `then`, and `else` as named nodes. This makes those expressions simpler to work with now that we can get the children directly.

### CODE REVIEW

**Comment by Razzeee** [comment]
So we would ask for unnamed nodes, if we need let or the others?

**Comment by jmbockhorst** [comment]
Yeah, I think so. I've already done much of the implementation on the language server to implement this. Although for some reason I couldn't build the .wasm bindings, so I haven't tested yet.

**Comment by Razzeee** [comment]
Sorry, we will just go by field in that case, should have read more of the PR before writing

**Comment by Razzeee** [comment]
This is great the field stuff actually was something that I wanted to do, but didn't find time for yet. Should I prepare another release or is there more that needs patching?

Regarding wasm, I recommend to do that via Docker.

**Comment by jmbockhorst** [comment]
I suspect I might need some tweaks or additions down the road when I implement it for type inference, but those shouldn't be much. I think we should get this released and integrated into the language server first. 

I was doing the wasm via Docker, but was getting errors.

**Pull request merged**
