### PR TITLE
Fixing named anonymous functions and floats not being recognized

### LINKED ISSUE #11: Named anonymous function
I've found this valid code in one of Elm repositories which fails parsing ([source](https://github.com/gampleman/elm-visualization/blob/c7aa9fb15bdb32cf75929c90bf161f5ac4025de1/src/Scale/Log.elm#L37)):
``` elm
makePows start base =
    if start < 0 then
        \x -> -(base ^ -x)

    else
        \x -> base ^ x
```
The following has to be added to `parse-examples`:
```
checkout_at "examples/elm-visualization" "gampleman/elm-visualization" "b666361498464845b2b9d3da4ff2661cb7f4ae4b"
```

I've attempted to write a test case for that, however I always ended up with a failure and not so much clue how I should continue with it. That's the test I've written:
```
=====================================
Named anonymous function
=====================================

makePows start base =
    if start < 0 then
        \x -> -(base ^ -x)

    else
        \x -> base ^ x

---
(file
        (value_declaration
                (function_declaration_left (lower_case_identifier) (lower_pattern (lower_case_identifier)) (lower_pattern (lower_case_identifier)))
                (eq)
                (if_else_expr
                        (if)
                        (bin_op_expr
                                (value_qid (lower_case_identifier))
                                (operator (operator_identifier))
                                (number_literal)
                        )
                        (then)
                        (anonymous_function_expr
                                (backslash)
                                (pattern (lower_pattern (lower_case_identifier)))
                                (arrow)
                                (negate_expr
                                        (parenthesized_expr
                                                (left_parenthesis)
                                                (bin_op_expr)
                                                (value_expr (value_qid (lower_case_identifier)))
                                                (bin_op_expr)
                                                (negate_expr
                                                        (operator_identifier)
                                                        (value_expr (value_qid (lower_case_identifier)))
                                                )
                                                (right_parenthesis)
                                        )
                                )
                        )
                        (else)
                        (anonymous_function_expr
                                (backslash)
                                (pattern (lower_pattern (lower_case_identifier)))
                                (arrow)
                                (value_expr (value_qid (lower_case_identifier)))
                                (operator (operator_identifier))
                                (value_expr (value_qid (lower_case_identifier)))
                        )
                )
        )
)
```

If you'd be able to point out what I did wrong - I'd appreciate it.

### PR DESCRIPTION
**Pull request by buinauskas**
Fixes #11 and #12

### CODE REVIEW

**Comment by Razzeee** [comment]
Please add a gitignore entry for the new example folders and remove the folders from git

**Comment by buinauskas** [comment]
@Razzeee have done it.

There are also some whitespaces being removed because of my VS Code config, those shouldn't cause any issues I would assume.

**Comment by Razzeee** [comment]
Can you please add a corpus test for the bracket after the minus?

**Comment by buinauskas** [comment]
Yes! 👍

**Comment by buinauskas** [comment]
@Razzeee that's been done :+1:

**Pull request merged**
